system/toggle-hidden-files.applescript

Open Raycast and type "toggle hidden files".
On Finder, the user will be able to see hidden files and folder which starts with a dot.
Difference between hidden files being presented or not

Add command to toggle hidden files

---

navigation/open-finder-from-terminal.applescript
navigation/open-terminal-from-finder.applescript

The script fails if iTerm is not installed. Now script will use `Terminal.app` only as a quick fix. iTerm support will be requested in a separate PR 🙂

fix(Finder & Terminal): iTerm support removed

---

.github/workflows/documentation.yml
Makefile
Tools/Toolkit/Sources/ToolkitLibrary/Models/RaycastData.swift
Tools/Toolkit/integration.sh

Fixes a small bug when the documents are generated (or regenerated) even without any changes on the script commands, we were committing the `extensions.json` with only the `lastUpdate` changed. 
The intention isn't make any commit using the Raycast Bot if we didn't explicitly made changes in two files: `commands/extensions.json` and `commands/README.md`.  This pull request is fixing that.
- Renamed `lastUpdate` key to `updatedAt`
- Workflow update
No apply
No apply

Workflow improvements

---

commands/media/spotify/spotify-now-playing-url.applescript

Allows the current playing Spotify song to be copied as a URL to the clipboard.
n/a

Add Script Commands: Spotify Now Playing Song URL to Clipboard #53

---

commands/media/spotify/spotify-now-playing-url.applescript

Switch the `raycast.icon` from `images/spotify.png` to `images/spotify-logo.png`, forgot to use the correct one.

Fix: use correct Spotify logo in copy now playing script

---

commands/system/define-word.swift

It adds a script command for looking up the definition of a word using the macOS dictionary.
N/A

Add script command: Define a word

---

commands/conversions/epoch-to-human-date.sh
commands/conversions/human-date-to-epoch.sh

- **Add Script Command**: human-date-to-epoch
- **Improvement**: Add argument support for epoch-to-human-date
- **Improvement**: add `-n` argument to echo when copy to clipboard, script won't print the trailing newline character anymore.
`date` is the shortcut set for epoch-to-human-date [**Already Have**]
`unix` is the shortcut set for human-date-to-epoch [**New Script**]
No dependencies required.

Add Script Command: human-date-to-epoch & Add argument support for epoch-to-human-date

---

commands/media/cmus/next-track.sh
commands/media/cmus/play-pause.sh
commands/media/cmus/previous-track.sh
commands/media/cmus/toggle-repeat.sh
commands/media/cmus/toggle-shuffle.sh
commands/media/cmus/track-info.sh

Adds script commands to control cmus music player.
[Cmus](https://github.com/cmus/cmus) music player can be downloaded through Homebrew:
```bash
brew install cmus
```

Add Script Commands: Cmus

---

commands/system/reload-coreaudio.sh

A new script, that fixes quality troubles with (at least) Bluetooth earphones by reloading `coreaudiod` process
<p align="center">
</p>
None

Reload CoreAudio script

---

commands/media/spotify/spotify-now-playing-url.applescript

Script has an effect on the system (inserts data to the clipboard), but this effect is not visible to user like `playNextTrack` for example (user can see the result of the script immediately (next track is playing), so the message may be needed, but at least not required).
<p align="center">
</p>

Output message added to copy current track URL script

---

commands/web-searches/wordpress/wordpress-classes-reference.sh
commands/web-searches/wordpress/wordpress-cli-command.sh
commands/web-searches/wordpress/wordpress-functions-reference.sh
commands/web-searches/wordpress/wordpress-hooks-reference.sh

Mistakenly did not add script for access to WP CLI commands reference on #126.
Also removes unnecessary slash from URLs.
- `open`

Add Script Command: wordpress-cli-command

---

commands/system/wallpaper-refresh.applescript

I think this worked for the currently focused display, but now seems to only work for the current Space of the main/primary display; adding clarity to the script's description.

Add specificity to description of wallpaper-refresh script

---

commands/web-searches/wordpress/wordpress-cli-command.sh

Adjust string replace to replace each space in input value with a forward slash (because there are no spaces in WP CLI commands).

Fix WP CLI command search

---

commands/web-searches/wpengine-install.sh

Revert incorrect change by @PitNikola in 4e33263f6d1f37d3fa03423a75875ca22bcec5b3. WP Engine installs do not have spaces, so any space should be removed from the install name.

Revert string replace in wpengine-install

---

commands/communication/xkcdpass.sh

Exclude newline when copying `xkcdpass` output.

Exclude newline when copying xkcdpass output

---

commands/developer-utils/decode-url.sh
commands/developer-utils/encode-url.sh
commands/developer-utils/escape-shell-chars.sh

PR adds three new scripts, one for decoding URLs, one for encoding URLs, and one script for escaping shell characters. The last one is especially handy for me when copying paths from remote servers and wanting to paste them with escaped backspaces.
The first two should be self-explanatory, so I'm only attaching the last one. Please let me know if you want gifs for the first two as well.
Escaping shell

add url decode/encode and escape-shell scripts

---

commands/media/apple-music/apple-music-set-volume.applescript
commands/media/apple-tv/apple-tv-set-volume.applescript

Music and TV have independent volume controls, so there should be script commands to control those. :wink:

Add Script Commands: set-volume for Music and TV

---

commands/system/sample-colour.swift

Use the new `NSColorSampler` to sample a colour from anywhere on the screen.
n/a

Add command to sample a colour from the screen

---

commands/system/sample-colour.swift

As reported on Slack, the sampled colour hex isn't always 6 digits. This uses Thomas' code to do so, though without the alpha value.
N/A
N/A

Improve the sampled colour hex to always return the full 6 digits

---

commands/developer-utils/is-it-up.sh

Add command to check if a website is up or not. It uses the isitup.org service.
N/A

Add command to check if a website is up or not

---

commands/dashboard/countdowns/countdown-to-date.template.sh
commands/dashboard/countdowns/create-countdown.template.sh

Fix the wrong `if` condition in countdown scripts

fix: wrong countdown condition

---

commands/developer-utils/sentry/sentry-unresolved-issues-by-project.py
commands/developer-utils/sentry/sentry-unresolved-issues-by-project.template.py

Adds a refactored version of [`sentry-unresolved-issues.template.py`](https://github.com/raycast/script-commands/blob/master/commands/developer-utils/sentry/sentry-unresolved-issues.template.py), which accepts a `Project` argument, and outputs all unresolved issues in the last 24h.
None

Add multi-project Sentry unresolved issues script

---

commands/developer-utils/github/open-gh-repo-pr-or-issue.sh

Do you already know which GitHub repo you want to open, and don't need to use the GitHub extension to search for a repository? Better yet, do you already know the specific pull request and/or issue by number? Then use this script command!
None

Add a script to visit a specific GitHub repo, pull request, or issue

---

commands/system/audio-output-switch.template.applescript

Switches audio output to desired output device. Example below shows HomePod.
Replace all instances of `<Device Name>` with the name of your desired audio output device

Add script for audio output switch

---

commands/dashboard/year-progress.sh

If day of the year returns number with prepended 0(zero) script can't
calculate progress with error: "Value too great for base" because
bash assumes it is octal number.

Fix decimal date calculation

---

commands/developer-utils/ip/get-external-ip-v4.sh
commands/developer-utils/ip/get-external-ip-v6.sh

A CAPTCHA prevents the script from working with ifconfig.co API.
Therefore, the script now uses the ipify.org API.

Update get external IP scripts to use ipify.org API instead of ifconfig.co

---

commands/developer-utils/create-image-from-code.sh

Update script `create-image-from-code.sh` to urlencode the base64 encoded code query param prior to generating URL to ray.so. Fixes issue #233. 
N/A
N/A

Fix bug 233. Urlencode the base64 encoded code prior to generating url

---

commands/web-searches/search-in-wikipedia.sh

Changes wikipedia search script to use wikipedia.org instead of chinese by default (zh)

Use wikipedia.org as default

---

commands/browsing/go-to-outine.sh
commands/developer-utils/error-info.sh
commands/developer-utils/whois.sh

I created a CLI to search about Apple API errors called [ErrorInfo](https://github.com/ronanrodrigo/ErrorInfo) and now I am adding it to the Raycast.
- brew
- mint
- errorinfo

Add error info

---

commands/developer-utils/sentry/sentry-unresolved-issues-by-project.template.py
commands/password-managers/bitwarden/search-vault-items.sh

Colorizes output for some `fullOutput` mode commands that I have contributed to this repo (`sentry/sentry-unresolved-issues-by-project` and `bitwarden/search-vault-items`).

Colorized command output

---

commands/conversions/what-day-is.py

Adds a script command to determine the day of the week on which a particular `YYYY-MM-DD` string fell/will fall. This was requested in the [Slack community](https://raycastcommunity.slack.com/archives/C01AC2X0GMN/p1613856204003100).

Add a date-to-weekday conversion script

---

commands/communication/slack/set-slack-DND-status.sh
commands/dashboard/countdowns/create-countdown.template.sh
commands/web-searches/bundlephobia.sh
commands/web-searches/caniuse.sh
commands/web-searches/crunchbase.sh
commands/web-searches/ecosia.sh
commands/web-searches/figma.sh
commands/web-searches/giphy.sh
commands/web-searches/grep-app-search.sh
commands/web-searches/mdn.sh
commands/web-searches/mozilla-developer-network.sh
commands/web-searches/njt.sh
commands/web-searches/npmjs.sh
commands/web-searches/npms.sh
commands/web-searches/repo.sh
commands/web-searches/search-cdnjs.sh
commands/web-searches/search-github.sh
commands/web-searches/search-netflix.sh
commands/web-searches/search-php-docs.sh
commands/web-searches/search-wpengine-installs.sh
commands/web-searches/twitter-search.sh
commands/web-searches/unfurl.sh
commands/web-searches/wayback-machine.sh
commands/web-searches/wordpress/search-wordpress-docs.sh
commands/web-searches/wordpress/wordpress-classes-reference.sh
commands/web-searches/wordpress/wordpress-functions-reference.sh
commands/web-searches/wordpress/wordpress-hooks-reference.sh

A quick update in the current base of Script Commands to use the argument key "percentEncoded" instead of the manual space replacement.

Update Script Commands to use percentEncoded key

---

README.md
Tools/Toolkit/Sources/ToolkitLibrary/Core/Documentation/Documentation.swift

A small addition of badges to our Awesome Script Commands ([commands/](https://github.com/raycast/script-commands/tree/master/commands) folder) and update the badge style in the main README.

Add badges to Awesome Script Command README

---

Tools/Toolkit/CONTRIBUTING.md

Updated a hyperlink from Toolkit's `CONTRIBUTING.md` that was pointing towards an invalid path.

Fix extension.json hyperlink

---

commands/developer-utils/run-bash-command.sh

Improve `developer-utils/run-bash-command.sh`:
1. Modify `$TERM` to `linux` to generate correct colored output, according to @grzegorzkrukowski 's [solution](https://github.com/raycast/script-commands/issues/22#issuecomment-789969644). 
2. Fix: if there's no open Finder window, the script with use `$HOME` as directory.
```bash
echo "Hello!"; echo "$(tput setaf 8)Hello!$(tput sgr0)"; echo "$(tput setaf 1)Hello!$(tput sgr0)";
```
**Before:**
**After:**
None.

Improve run-bash-command.sh

---

commands/communication/slack/set-slack-DND-status.sh

Just a little PR to fix default duration in `set-slack-DND-status.sh`

Slack DND script - allow default status expiration

---

commands/system/empty-trash.applescript

This change suppresses the error 128 when emptying an already empty Trash.

fix error 128

---

commands/media/apple-music/apple-music-go-to-artist-page.sh

This command provides a convenient way to open an artist's page in Apple Music. It works most of the time, but you'll get the best results using the exact artist's name: it currently just opens the first result of the query. When the RayCast API is available I'll implement something proper.
There is a dependency on jq. Install using `brew install jq`

Go to a an artists page in apple music

---

commands/system/quit-app.swift

Script that takes in a name or a process id and terminates it. I, personally, use it with "kill process" instead of "quit app", but not everyone is technical, so I went with a more friendly name for the public version. But I'm up for debate on this one, because I'm not totally sure how it should go for the public. I also tried "Terminate app", but that also didn't feel right.

Quit app script

---

commands/system/network-status.sh

System script that detects your current network connections. It can have the following states:
* `Ethernet`
* `Ethernet | <wifi-name>`
* `<wifi-name>`
* `No connection`
I'm open to any feedback 🙂. For the icon I have also considered these 2 emojis 🌐 📡, and the `wifi` segment was initially using this style `Wi-fi (<wifi-name>)`
https://user-images.githubusercontent.com/32957606/110263534-debba600-7f6b-11eb-9d99-c0f6c8e535cb.mov

New Script: network-status.sh

---

commands/developer-utils/generate-git-ignore.sh

Calls https://gitignore.io to generate a `.gitignore` file for the given technologies and copies the result to clipboard.

Script to generate gitignore file

---

commands/password-managers/bitwarden/copy-first-matching-password.sh

This is fixing a bug that was adding a newline at the end of the copied password and a bug on displayed message when copying password for a non-existing account (example bellow)
The first call is performed before changes, the second one is before after my changes.
- [ x] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

bitwarden: fix clipboard copy error that may include newline and message when copying password for a non-existing account

---

commands/system/list-processes.rb

Lists a given number of processes, showing name, process id and CPU usage (ordered by it). The parameter is optional, falling back to 15, which I felt is a reasonable amount to be easily readable, but also to provide enough information.
One of the big downsides of this is that when it runs, it slightly spikes in CPU usage, making Raycast and ruby always appear in the list as high usage. Not really sure that we should ignore them, either 🤔

List processes script

---

commands/developer-utils/create-image-from-code.sh

@thomaspaulmann : if the title contains spaces (maybe other characters), the command fails.
Using php as it should be available on every macOS, and I couldn't find an easy bash way to do it.
This uses php CLI, which should be available on every macOS.

Suggestion: url encode the title

---

commands/system/uninstall-with-appcleaner.applescript

Add script to uninstall apps with [AppCleaner](https://freemacsoft.net/appcleaner/).
Requires the installation of AppCleaner: `brew install --cask appcleaner` or <https://freemacsoft.net/appcleaner/>

Add script to uninstall apps with AppCleaner

---

commands/communication/text/unicode-superscript.sh
commands/conversions/unicode-superscript.sh

Converts text to fake unicode ˢᵘᵖᵉʳˢᶜʳᶦᵖᵗ.
Only default macOS dependencies.

unicode superscript

---

commands/communication/rich-text-clipboard-to-markdown.sh
commands/system/rich-text-clipboard-to-markdown.sh

1. pastes clipboard as html through applescript call
2. processes output with perl to plain text
3. uses pandoc to convert html to github flavoured markdown
4. puts result back on clipboard
^ now outputs github flavoured markdown instead.
Requires [pandoc](https://pandoc.org/).
`brew install pandoc`

Rich text to markdown

---

commands/developer-utils/ignore-package-folders-time-machine.sh

Searches for a set of given folders (package folders) and excludes them from Time Machine backups. It then runs this daily and displays when it was last ran at.

Script to ignore package folders from Time Machine backups

---

commands/system/open-folder.sh

Update script `open folder`, this modification is more reasonable. 
The current version supports the case where the name of the home directory is different from the account name. The old version doesn't.

update script command: open folder

---

commands/conversions/epoch-to-human-date.sh

Current command of `epoch-to-human-date.sh` only supports Unix time in seconds. This pull request enables conversion from Unix time in milliseconds.
Not a new script.
Not needed.

Support conversion of epoch in milliseconds for epoch-to-human-date.sh

---

commands/conversions/unix-time-reader.sh

Display Human-Readable Date from Unix Time in Pasteboard.
There is aleady a `epoch-to-human-date.sh` in this repository and I opened a pull request #339  about it just earlier today.
But Unix Time Reader is so different that I decided to make it as a new script. Specifically, it does not require any arguments, displays result in `compact` mode instead of the fleeting `silent` mode and does not copy the result to the clipboard. It also handles error.

Add new conversion script "Unix Time Reader"

---

commands/apps/deepl/deepl-web-translate.sh

Fix missing space in the if statement brackets

Fix missing space in the if statement brackets

---

commands/communication/google-meet/meet.sh

Add brave browser support to *Open Google Meet* script

Update Script: Open Google Meet: Add Brave support

---

commands/developer-utils/check-domain.template.sh

This command uses the [Vercel](https://vercel.com/) API [domains endpoint](https://vercel.com/docs/api#endpoints/domains) to check a domain name's availability. The command takes a single argument, a domain name string, with placeholder `example.com`. If the domain is for sale, the command outputs its price to the user. If not, the user is told. If an auth or other error occurs, the user is alerted and the command throws an error with `exit 1`.
I've placed the script file in the root of `commands/developer-utils` because the functionality is fairly general. In the future, a dedicated `vercel` folder could cover Vercel-specific functionality.
👋  This is my first time contributing to a real open-source project so thank you for bearing with me! I'm likely missing some important steps so any …

🌐 Add command to check domain name availability

---

commands/conversions/vaporwave-text.sh

1. New script: Converts 'vaporwave text' to 'ｖａｐｏｒｗａｖｅ　ｔｅｘｔ'
2. change to unicode superscript script to avoid Bash → JXA bug with non-percent-encoded strings. (i.e. `"`)
No requirements outside base macOS.

add  ｖａｐｏｒｗａｖｅ text conversion script.

---

commands/conversions/unicode-superscript.sh

use percent encoding to avoid a string bug. decode in jxa javascript.

Fix bug with superscript script & bash -> jxa

---

commands/communication/say.sh

Add command `communication/say.sh` that converts text to audible speech. It is just a wrapper for the CLI command `say` that's built-in macOS.

Add command to say things

---

commands/system/open-selection-with.applescript

Open selected items in Finder with the given application. 
https://user-images.githubusercontent.com/365403/114734941-152ed280-9d1b-11eb-9d36-e5d5fc8bdf7d.mp4

Command to open Finder selection with a given app

---

commands/system/audio/get-selected-audio-device.swift
commands/system/audio/set-audio-device.swift

Improved the set audio device script to work with a "both" option. Also added a script to display currently selected devices.

Set audio improvements

---

commands/system/empty-clipboard.sh

It is a command to empty clipboard. Can be useful if you have some sensitive information in it and wanna it to be cleaned.
Nope

add "Empty Clipboard" command

---

commands/system/disk-usage.sh

Adds an inline script command to display the disk usage of your / (root).
It can relatively easily be adapted to a different disk, or even multiple disks.
N/A

Add script command: Show disk usage of / (root)

---

commands/system/empty-clipboard.sh

Changed output of "Empty Clipboard" command to be consistent with "Empty Trash" in std
nil

changed "Empty Clipboard" output

---

commands/dashboard/sabnzbd-queue-status.template.sh

Displays some of the status points from the full queue status. To see what else is available, look at the [wiki](https://sabnzbd.org/wiki/advanced/api#queue).
For users of [SABnzbd](https://sabnzbd.org/)

Add SABnzbd queue status

---

commands/apps/translate-shell/translate-shell-language-pair.py
commands/apps/translate-shell/translate-to-en.sh
commands/apps/translate-shell/translate-to-zh.sh
commands/web-searches/search-emojipedia.sh

This script lets the user configure a language-pair and uses it to
translate words for these languages in both directions.
The first result is copied to the clipboard.
https://user-images.githubusercontent.com/4022103/117363464-e7255400-aebc-11eb-8de7-5721356d8821.mov
[Translate-Shell](https://www.soimort.org/translate-shell)

translate-shell: Add script to translate into a favorite language-pair

---

commands/browsing/chrome-current-page-url.sh

Add 'Copy Current Page URL' for Google Chrome

Add 'Copy Current Page URL' for Google Chrome

---

commands/system/create-new-file.applescript

When I run '/script-commands/commands/system/create-new-file-in-finder.applescript' the file, I found a vulnerability: when the script is used to create a file in the folder, if the file "untitled.txt" with the same name already exists in the folder, the script will return an error prompt: "there is a file with the same name". 
Therefore, based on the source file and according to my personal usage habits, I have made appropriate modifications to the part of the code that I think needs to be improved.
none.

Improvement of an existing script:create-new-file-in-finder.applescript

---

commands/apps/mail/copy-foreground-mail-deeplink.applescript

This PR adds a script command that will, if Mail is the most foreground app, copy the deeplink to the selected emails (as a comma delimited list).
There isn't an easy way to get a screenshot and a gif would expose the contents of my Mail. 😰 
N/A

Add script: Copy deeplinks to emails in Mail

---

commands/README.md
commands/navigation/open-finder.sh

Adding a Finder command to open $HOME by default (no option given), or an absolute path if the argument starts with '/', or relative to $HOME if the argument doesn't start with '/'.

Adding Finder command to open any location

---

.github/workflows/script-commands.yml

Currently the Toolkit isn't setting the right dates for scripts in the `extensions.json` file. These dates are retrieved from the git history via the git cli. The github's checkout action have a parameter `fetch-depth` with is set to 1 by default, this involves that git doesn’t get the full git log history. Setting it to 0 as should fix the history problem and then the weird behaviour of the command. :smile:

Fix Toolkit that isn't retrieving the right createdDate and updatedDate for scripts

---

commands/conversions/strikethrough.sh

Text strikethrough - works with either given input or clipboard (when no argument).

Add text strikethrough

---

commands/system/update-scripts-command.template.py

Improving [update-scripts-command](https://github.com/raycast/script-commands/blob/master/commands/system/update-scripts-command.template.py) to handle script versionning using the [file](https://github.com/raycast/script-commands/blob/master/commands/extensions.json) generated by the Toolkit.
It now only updates when needed and the user's feedback about what happened is improved.
See #448

Added handling of versioning using extension.json on the update-script-command

---

commands/system/flush-dns.sh

Flushes macOS DNS cache.
None.

Add command to flush DNS cache

---

commands/apps/bear/bear-search.sh

Bear doesn't seem to like blank args in the `x-callback-url`, so only send the args that are supplied.
Specifically, if you specify a `term` but not a `tag`, Bear seems to not do a search at all. Sending only the `term` in the call results in correct search.
n/a
n/a

Don't send blank args in x-callback-url

---

commands/developer-utils/count-characters.py

Counts the characters of either the clipboard or the passed argument.
Needs python 3.x and the [pasteboard library](https://github.com/tobywf/pasteboard).

Add character count command

---

commands/password-managers/bitwarden/unlock.sh

Fix issue that passwords with spaces were detected as invalid

Bitwarden: Fix issue that passwords with spaces were detected as invalid

---

commands/password-managers/bitwarden/copy-first-matching-password.sh

Notify the user if the searched password was not found.

Bitwarden: Actually print an error message if no result was found

---

commands/communication/google-meet/meet.sh

Better URL to create a new Google Meet in the `communication/google-meet/meet.sh` script. The copied URL will look like `https://meet.google.com/xxx-xxxx-xxx` instead of `https://meet.google.com/xxx-xxxx-xxx?authuser=0`.

Better link for new google meet

---

commands/apps/translate-shell/translate-shell-language-pair.py

The current approach wasn't very clear how the PATH variable was used
later in the script.
Not the actual required binaries can be changed and are being used.

translate-shell: Change setting for trans and gawk binaries

---

commands/system/sample-color.swift

Swift uses "color", so I felt that using modifying it to be consistent would be better. Also, I renamed the title so that typing "sample color" or "sample colour" would work.

Change "colour" to "color"

---

Tools/Toolkit/Package.resolved
Tools/Toolkit/Sources/ToolkitLibrary/Core/Toolkit/Toolkit+Constants.swift
Tools/Toolkit/Sources/ToolkitLibrary/Core/Toolkit/Toolkit+ReadContent.swift
Tools/Toolkit/Sources/ToolkitLibrary/Models/Language.swift

Just few improvements in the Toolkit to make the generation of the README and the extensions.json even better
What was improved:

Small improvements in Toolkit

---

commands/apps/notes/open-note.applescript
commands/apps/notes/search-notes.applescript

Simply allows you to search your notes via title. 
Note: titles need to be exact matches in order to query them properly and in the event that you have mutliple of the same titles, it'll choose the most recently edited one to display. 
https://user-images.githubusercontent.com/46573539/127367109-8e84d725-2178-40c4-a1c4-0d68c13f325b.mov
No reqs/depedencies required.

New script to search notes via title

---

commands/apps/safari/safari-clear-cache-reload.applescript

This script use the option-command-R keyboard shortcut to force refresh a Safari page. It arose out of a need to get a current CI badge status when using Github Action workflows because I noticed that the badge would not reflect the current status unless cache was cleared and the page refreshed. Normally that requires enabling Developer Menu and opt-cmd-E and cmd-R, but opt-cmd-R seems to do both and doesn't require enabling Developer Mode. Having this in Raycast is just one less thing to remember and it's nice to have it stored centrally.
Not much to see here...it just force refreshes the frontmost safari page. I added a comment about this being undocumented and therefore subject to change w/o notice. 
none

adding force refresh script

---

commands/media/apple-music/apple-music-search.applescript

This is a script that operates directly on the Music/iTunes app interface. 
It's actually doing copy-and-paste so it replaces your clipboard for a few seconds and then restores it. This enables inputting more languages than keystrokes. 
https://user-images.githubusercontent.com/40051361/129825589-bdee76f9-9597-4a5d-87e3-19d03b18b3d1.mov
The script detects the window's title to determine whether you're in the library view so that it could handle it while you have the mini-player opened or there's no window. However, the title varies depending on the app's language and I haven't actually tested it with iTunes. **Please add the window's title to the array in the script file if it doesn't work.**

Create Apple Music Search script command

---

commands/developer-utils/unshorten-url.sh

This PR adds a Developer Util to resolve short URLs. I personally find it useful since most of short url services are blocked in my home network. 
This script depends on https://unshorten.me/api

Added command to resolve short urls

---

commands/productivity/imgur-upload-latest-screenshot.template.sh
commands/productivity/last2imgur.sh

It's a very simple script command that uploads the latest screenshot to Imgur and copies the image link to clipboard.
Uploading to Imgur does require an API, I have created an application and put the client id, you can put your own API as well . Imgur allows for 1.25k images per day for free api so you might want to use your own depending on your use-case. [Imgur API](https://api.imgur.com/oauth2/addclient)

Added command to upload latest screenshot to Imgur

---

commands/apps/safari/safari-current-page-url-in-chrome.applescript
commands/apps/safari/safari-current-page-url-in-firefox.applescript

Open the URL of the current page in Safari in a different browser (Chrome or Firefox).
Self explanatory.
None.

Open current Safari URL in a different browser

---

commands/apps/notes/search-note-by-name.applescript

This script searches for a note, given its exact name, or a substring, the search does not consider case, if two notes or more have the same given substring, the script will always show the first one.
https://user-images.githubusercontent.com/841163/130208036-d2e623e6-831d-4ed7-b637-bae05fe44821.mov

add search-note-by-name script

---

commands/developer-utils/open-link-simulator.applescript

Very excited to be sharing my first script with the community 🎉 
This script open the inputted URL on the iOS simulator that is currently booted, which also includes URL Schemes and Universal Links. This has been really handy when I need to test a deep link in my apps

Added Open URL in iOS Simulator script

---

commands/conversions/create-markdown-table.js

Adds a new script that enables creating a markdown table from column & row inputs. I used to love this script with Alfred, bringing it over to Raycast.
Simply input something like `table 3 2` to copy to clipboard:
```
|   |   |   |
|---|---|---|
|   |   |   |
|   |   |   |
```
Node

Add script to generate markdown tables from column + row input

---

commands/system/audio/audio-output-switch.template.applescript

It was brought to my attention by @dehesa that the `audio-output-switch` script I created was no longer working in macOS Monterey. From what I gathered it seems the error occurs due to the fact that Monterey now displays "Loading Sound..." for a moment while the preference pane is populated. Adding a simple 1 second delay to the script seems to fix the issue for me.

Fix `audio-output-switch` for Monterey

---

commands/productivity/tesseract/tesseract-ocr.sh

Fix locale and use one temp file

tesseract-ocr: Fix locale and use one temp file

---

commands/math/random-number.sh

Signed-off-by: Matt Gleich <git@mattglei.ch>
This script-command allows the user to generate a number between a given range quickly
https://user-images.githubusercontent.com/43759105/141932900-d38b2af1-a3f6-44d0-b21d-29db52e10dbd.mov
`jot` and `pbcopy` are included by default in macOS

feat: random-number script command

---

commands/developer-utils/create-image-from-code.sh

`language=c-like` doesn't work, replace by `language=cpp`

Change `c-like` to `cpp`

---

commands/communication/call-with-iphone.sh

Add a basic script using the native Cellular Call Feature provided by Apple. There is no easy way to make a normal telephone call other than using the Contacts app or FaceTime (although the UX for this feature has gotten worse in Monterey. 
See: https://support.apple.com/en-ca/HT209456 
This script uses the "iPhone Cellular Call Feature" provided by apple to quickly make telephone calls without having to go via Contacts. Added one second of sleep to allow an individual to consider whether it was a mistake. It happens.
As simple as can be:
None.

Add script to place call via Apple's Cellular Calls feature

---

commands/apps/deepl/deepl-app-translate.applescript

DeepL app translate was not working after upgrading to version 3.0 because the gui changed slightly

Fix DeepL app translate script for app v3

---

commands/communication/slack/add-slack-reminder.template.sh

Adds a new script command bash template for creating a reminder on slack using their reminders endpoint
https://api.slack.com/methods/reminders.add
https://user-images.githubusercontent.com/2199845/149343775-abe8681b-a0e3-42bb-b640-e02fcff6f3e6.mov
Then see your reminders in slack with `/remind list` command
Your new reminder should show up!

add command template for creating a reminder on slack

---

commands/system/toggle-desktop-icons.applescript

Wait the Finder process not exit after quit Finder, then activate Finder, otherwise activate will always failed.

Improve relaunch Finder in toggle-desktop-icons(system)

---

commands/developer-utils/ip/get-external-ip-v4.sh
commands/developer-utils/ip/get-external-ip-v6.sh
commands/developer-utils/ip/get-local-ip-v4.sh
commands/developer-utils/ip/get-local-ip-v6.sh

These ip script were copying the ip with a space at the end; 'xx.xx.xxx.xx ', fixed that so there is no more blank space at the end.
None

Fix copy ip blank space

---

commands/math/latex-calculator.py

Signed-off-by: Matt Gleich <git@mattglei.ch>
Allow the user to input a LaTeX math expression and have the evaluated product be copied to their clipboard.
https://user-images.githubusercontent.com/43759105/152477036-0e2acf17-b633-4536-a8df-516a348b9bcc.mov
This script command requires pyperclip, sympy, and antlr4-python3-runtime. They can all be installed using the following commands:
```bash
pip3 install pyperclip
pip3 install sympy
pip3 install antlr4-python3-runtime==4.7.2
```

feat: latex-calculator script command

---

commands/system/audio/airpodsbattery.sh

Fix the `system/audio/airpodsbattery.sh` extension to work properly with AirPods 3rd gen.
Before
After
N/A

system/audio/airpodsbatter.sh: add product id for airpods 3rd gen

---

commands/conversions/change-case/snakecase.py

The original snake_case script converted `CamelCaseExample` to `camelcaseexample`. This PR fixes the problem so `CamelCaseExample` correctly becomes `camel_case_example`.

Allowed conversion from CamelCase to snake_case in the `snakecase.py` script

---

commands/system/close-finder-windows.applescript

As you may know, it is not easy to close multiple open Finder windows without using the Finder-specific keyboard shortcut. This AppleScript will close all windows while keeping other apps open and Finder without forcing Finder to close and reopen.
None

Add close all Finder windows command.

---

commands/apps/hyper/hyper-run-shell-command.applescript

Add `# @raycast.currentDirectoryPath ~` to the applescript, because without it, the script can't find `./.hyper_plugins/hyperalfred.txt`
No, I can't use `~/.hyper_plugins/hyperalfred.txt` because the script returns a permissions error

[Hyper] Fix Hyper integration

---

commands/browsing/safari-current-page-url.sh

Strips whitespace when copying current Safari page URL.

Safari: Strip whitespace when copying current page URL

---

commands/system/battery-info.sh

Script command that shows various battery info like Battery Percentage, Cycle Count, Time remaining to deplete/fuly charge, current wattage of power connected etc. 
None

add: add battery info script command

---

commands/navigation/open-last-downloaded.sh

A simple script to open the last downloaded file.
Feature request: would be great if a modifier could be passed to a script so this could easily "view in finder" the last file instead of opening.
Worth noting that after I wrote this I found there was a swift script that did something similar. This shell script is ~10x faster and easier to understand, which is why I'm still submitting this PR.
Hopefully it is simple enough this isn't needed.
N/A

Adding open last downloaded script

---

commands/conversions/paste-as-plain-text.applescript
commands/conversions/paste-as-plain-text.sh

This is a follow-up to https://github.com/raycast/script-commands/pull/685
This command executes the "paste as plain text" menu item. The reason this is useful is there are some applications,
such as google sheets, which disable menu item although it can still be used. This command allows you to use this
menu item consistently regardless of if the application decides to disable the hotkeys associated with it.
In original PR.
N/A

Click paste as plain text command

---

commands/dashboard/open-weather/weather-current.template.sh
commands/dashboard/open-weather/weather-forecast.template.sh

Added OpenWeather template scripts for forecast and current weather. 
Forecast script is displaying day and night temperature for today and the next 3 days.
current weather dark mode:
current weather light mode:
forecast dark mode:
forecast light mode:
1. Create an OpenWeather account here: https://home.openweathermap.org/
2. Generate free API KEY here: https://home.openweathermap.org/api_keys
3. Fill in the API_KEY and CITY variables in the script

OpenWeather current and forecast scripts

---

commands/system/network-quality.sh

Network Quality CLI Command for macOS aka Speedtest command.  Slack thread [here](https://raycastcommunity.slack.com/archives/C01AC2X0GMN/p1649876221157519).
No dependencies required the command exists within macOS.

Add Network Quality CLI Command

---

commands/developer-utils/copy-focused-finder-window-path.sh

Copies the absolute path of the currently focused Finder window.
Requires macOS (as Finder is available only on macOS). :)

Add "Copy Focused Finder Window Path"

---

commands/system/audio/get-audio-devices.swift
commands/system/audio/get-selected-audio-device.swift
commands/system/audio/set-audio-device.swift

The CoreAudio related swift scripts serves as an example of CoreAudio usage, but I found some minor issues with these scripts, and here are some quick fixes:
1. `kAudioObjectPropertyElementMaster` has been renamed to `kAudioObjectPropertyElementMain` on macOS 12 SDK. This PR makes essential adjustments so that it reportes no warnings while remaining backward compatible.
2. The third argument of `AudioObjectGetPropertyDataSize` should be 0 if the fourth argument is `nil`.
3. `kAudioDevicePropertyDeviceNameCFString` is in `CoreAudio/AudioHardwareDeprecated.h` and `kAudioObjectPropertyName` should be used instead.

Update CoreAudio related swift scripts.

---

README.md

Original link for feedback email was a link to `https://github.com/raycast/script-commands/feedback@raycast.com` which is not valid.
Changed to `mailto:feedback@raycast.com` which is valid.
Another option is to present the link in a code block, that is `feedback@raycast.com`, which IMO is the better option since practically nobody really likes clicking `mailto:` links and has his email setup. I reckon most people that are inclined to send an email would copy the email address.

Update README.md's email address

---

commands/system/save-image-from-clipboard.py

This PR fixes a typo about library name.

fix library name typo

---

commands/browsing/short-url-emoji.sh

Adds script to turn https://www.raycast.com/blog/making-a-raycast-wallpaper/ into https://bne.sh/🍗🚥🧏‍♂️
https://bne.sh/create lets you make URLs but this script lets you make a short url for free
NA

add custom script that adds short urls with emojis 

---

commands/developer-utils/minikube/minikube-config-set.sh
commands/developer-utils/minikube/minikube-pause.sh
commands/developer-utils/minikube/minikube-start.sh
commands/developer-utils/minikube/minikube-status.sh
commands/developer-utils/minikube/minikube-stop.sh
commands/developer-utils/minikube/minikube-unpause.sh

This set of scripts allows users to interact with a local/remote `minikube` cluster, without leaving Raycast.
Obviously needs Minikube itself.
https://minikube.sigs.k8s.io/

feat: Add minikube commands

---

commands/system/toggle-battery-charging.sh

You can toggle battery charging with this script. It depends on [smc](https://github.com/hholtmann/smcFanControl/tree/master/smc-command) to change 2 flags and enable/disable battery charging.
After changing it, it takes 30 - 70 seconds to effect and change the battery icon on menubar.
1- run "curl https://raw.githubusercontent.com/actuallymentor/battery/main/setup.sh | sudo bash" to install smc and battery script
2- run "battery visudo" to add battery command to sudoers

feat: add toggle battery charging script

---

commands/developer-utils/copy-ssh-public-key.sh

This command will copy the default public SSH key to the clipboard in order to paste it on another machine's `authorized_hosts` file or on a third-party service (AWS, DigitalOcean, etc.)
None

Add copy-ssh-public-key command

---

commands/writing/dictionary-lookup.swift

Although a "Define Word" command already exists, it's currently requiring the user to select one potential entry before getting the actual definition. 
This Script Command uses macOS's DictionaryServices to query a word or phrase to the active dictionaries and return them directly, without having to switch from screens or pressing "Enter."

Add dictionary lookup command

---

commands/conversions/clipboard-to-markdown.js

This PR introduces a simple "Clipboard to Markdown" script, which allows to convert of simple content stored in the Clipboard to Markdown without any external services.
Currently, it supports regular links, images, lists, and images and links in the line items.
- NodeJS

Adds Clipboard to Markdown script

---

commands/web-searches/clipboard-to-17track.js

This PR introduces a "Clipboard to 17TRACK" script, which opens a 17track.net page with whichever tracking code was stored in the user's clipboard to get easy access to tracking information, provider, et al.
- NodeJS

Add Clipboard to 17TRACK script

---

commands/developer-utils/vscode/open-folder-in-vscode.applescript
commands/developer-utils/vscode/open-project-in-vscode.sh

Hi,
I just found some formatting errors in your README which made it slightly harder for me to find scripts for VS Code. In the descriptions of the VS Code scripts, the authors have referred VS Code both as VScode and vs Code. In this commit, I've standardized it to VS Code, along with changing git to Git. Furthermore, in the name field of `extensions.json` (and therefore on `README.md`), the [name is spelled Vscode](https://github.com/safwansamsudeen/script-commands/blob/defd6466287163dae800a4a13b0b5afa145a2acf/commands/extensions.json#L9986) - could you change that too to VS Code? I would, but the Contribution Guidelines told me not to modify these files. 
Just a minor aesthetic, and thanks!

Fix formatting of descriptions in VS Code related scripts

---

commands/apps/warp/warp-start.sh
commands/apps/warp/warp-status.sh
commands/apps/warp/warp-stop.sh
commands/apps/warp/warp-toggle.sh

- The `warp-cli status` command output order is not guaranteed so the script fails sometimes.
- Using `grep Status` to get the line with status instead of fixing to the second line.

fix: warp commands fail sometimes due to the order of output

---

commands/web-searches/doi-clipboard.sh
commands/web-searches/doi.sh

This is a package that parses a doi string (unique digital object identifier used to identify academic, professional, and government information) and opens the corresponding resource. 
It supports the following formats: doi:10.* (e.g. doi:10.1136/bmj.k5094) , 10.* (e.g. 10.1136/bmj.k5094) , doi/10.* (e.g. doi/10.1136/bmj.k5094), and doi: 10.* (e.g. doi: 10.1136/bmj.k5094).
There is an additional command that scans the clipboard and identifies doi strings rather than waiting for the user to paste it into Raycast. (see second screenshot)
No.

feat(browsing): command for doi string parsing

---

commands/dashboard/firebase/firebase-authentication-get-token.template.sh

This PR adds a script to generate authentication tokens using the Firebase Authentication service.
Install via homebrew: `brew install jq`
You can find API_KEY on the "Project settings -> General" page in Firebase.
You need to create a user with email and password on the "Authentication -> Users" page in Firebase.

feat: add a script to get authorization tokens from Firebase Authentication service

---

commands/conversions/clipboard-ocr.sh
commands/system/open-image-from-clipboard.sh

Dependency: `brew install pngpaste coreutils`
pngpaste required to grab image from clipboard
coreutils required to create temp file with suffix

add open image from clipboard & clipboard OCR

---

commands/developer-utils/clear_xcode.sh

Update the command adding escaping character for the spaces on `iOS Device Logs` folder generated by Xcode
N/A
N/A

Fix command to remove iOS Device Logs folder

---

commands/apps/safari/safari-bing-edge-user-agent.applescript

I'd like to try #820, but when I added the `safari` folder as my script directory, I can't find it in the script commands.
After discovering that the issue was caused by the file encoding, I changed it to UTF-8, which resolved the problem.

Fix file encoding

---

commands/developer-utils/is-it-up.sh

Updated script to work with urls with http://, https://, and www. without giving an error.
Updated command to fix a common bug. 
Bug fix / expansion of functionality.
- [  ] New script command
- [ x ] Bug fix
- [ x ] Improvement of an existing script
- [  ] Documentation update
- [  ] Toolkit change
- [  ] Other (Specify)
- [ x ] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)

Updated functionality of is-it-up.sh

---

commands/communication/zoom/rename-profile.applescript

[![zoom-rename.gif](https://i.postimg.cc/JhBSPpBK/zoom-rename.gif)](https://postimg.cc/TyfkPq0W)
To use this script, you will need cliclick installed on your machine. You can install it via Homebrew using the command `brew install cliclick`.
Once installed, open a terminal and run the command `which cliclick` to get its path. For example, the output might be `/opt/homebrew/bin/cliclick`. Replace the path in the script with the one you obtained. This script may become outdated if Zoom App updates its layout in the future. Manual fine tuning the x,y of mouse coordinates may necessary.

feat(zoom): add zoom rename profile script

---

commands/productivity/imgur/imgur-upload-clipboard-image.template.sh

After testing, the url returned by the current imgur api contains an escape for "/". 
The response is like: `"link":"https:\/\/i.imgur.com\/0UTnNoS.png"`.
So I added a simple sed command to correct the parsing of links.

Update imgur-upload-clipboard-image.template.sh to fix url parsing.

---

commands/apps/warp/warp-reauth.sh

Adds a missing command to the WARP package - reauthenticate.
In our usecase, just toggling Warp is not enough - we have day-long sessions so we need to trigger a reauth manually a lot.
WARP CLI (nothing new WARP related).

Add Warp reauth command

---

commands/browsing/convert-twitter-to-nitter.js

A new script command that takes in a twitter link as an argument and converts it to a nitter.net link and open it in the default browser.
[Passing a Twitter link as an argument](https://imgur.com/u5L8Vau)
[Opening a new browser window with a prompt](https://imgur.com/Vo63WZG)
[Opened link](https://imgur.com/LNuQZiE)
None

✨ add command to convert twitter link to nitter

---

commands/developer-utils/join-lines.sh

Adds a new script command that joins multiple lines of text from the clipboard into a single line, separated by a specified delimiter.
Suppose the clipboard content is as follows and the delimiter specified is `-`:
```
apple
banana
cherry
```
This will result in the new clipboard content being:
```
apple-banana-cherry
```
None

Add command to join clipboard lines by delimiter

---

commands/system/toggle-lid-sleep.sh

Added a new script command that toggles macOS setting that prevents laptop from going to sleep when lid's closed:

added command to toggle sleep when laptop lid's closed

---

commands/developer-utils/view-scripting-dictionary.sh

Added a new script command that opens the Scripting Dictionary for the frontmost application or the application specified via the argument. If an application doesn't have a scripting dictionary, the error is handled by Script Editor.
None beyond base macOS.

feat: Add View Scripting Dictionary command

---

commands/communication/slack/slack-dev-mode.sh

This is a very simple command that launches Slack with the Developer Menu (Electron Dev Tools) enabled via `⌘+⌥+I`.

feat(communication/slack): slack-dev-mode script

---

commands/apps/notes/create-note-from-clipboard.applescript

Fixed issue with double-pasting of titles.
PR sets title correctly:

[Apple Notes] Fixed title issue

---

commands/system/default-browser-front-most-app.applescript

Updated default-browser-front-most-app.applescript to fix a bug with Firefox Development Edition browser and add a new browser SigmaOS.
- Firexfox Developer Edition was not working as chrome dev was catching any browser with dev in the name before it could get to firefox dev, moved firefox dev before chrome to allow both to catch properly.
- Added SigmaOS to browser list.

Update default-browser-front-most-app - Firefoc dev and SigmaOS

---

commands/system/toggle-natural-scrolling.applescript

The current natural scrolling script doesn't work in latest macos version 14 (Sonama). I think this has been broken for a while (after Ventura), based on my research, but I can't confirm it. This change fixes the script to work correctly for macos 14 (Sonama) and higher and keeps the old script for older versions. I think the same new script would work for older versions as well, but I can't test that, so I've kept the old script under the else block.

Fix: Natural Scrolling Script for latest macos versions

---

commands/conversions/markdown-to-telegram.py

This script converts Markdown-formatted text into a Telegram-compatible format. It automatically transforms various Markdown formatting elements, such as headers, bold, italic, strikethrough, spoilers, underline, links, and inline code, into their corresponding Telegram formatting tags. The script also adds emojis before different header levels and inserts empty lines between paragraphs to improve readability.
This tool is particularly useful for those who frequently work with Markdown documentation and want to quickly share it on Telegram while preserving most of the original formatting. Instead of manually altering the syntax for each formatting element, users can simply copy their Markdown text, run this script, and have the formatted version ready to paste directly into a Telegram …

Script for convert Markdown formatting to Telegram format

---

commands/system/ocr.swift

Previously, Chinese could not be recognized by OCR, it was all garbled.
Correct the OCR command by updating the 'recognition languages' parameters; this will ensure both Chinese and English are recognized accurately.
Reference:
To recognize traditional and simplified Chinese, specify zh-Hant and zh-Hans as the first elements in the request’s recognitionLanguages property. English is the only other language that you can pair with Chinese. https://developer.apple.com/documentation/vision/original_objective-c_and_swift_api/recognizing_text_in_images

Fix: ocr command by updating recognitionlangues params

---

templates/script-command.template.applescript
templates/script-command.template.php
templates/script-command.template.py
templates/script-command.template.rb
templates/script-command.template.sh
templates/script-command.template.swift

In the instruction comments for each script template there is a comment that says:
`// Duplicate this file and remove ".template." from the filename to get started.`
The full file path is, for example, `../raycast scripts/script-command.template.sh` so following this instruction as is would result (undesirebly) in:
`../raycast scripts/script-commandsh`
which isn't a valid file. So the instruction should be:
`// Duplicate this file and remove ".template" from the filename to get started.`
The .js file templates/script-command.template.js did not have this issue so it is not touched in this commit/PR.
n/a
n/a

Remove superfluous period from all script template renaming instructions

---

commands/communication/duckduckgo-email-protection/generate-unique-email-address.applescript

DuckDuckGo has modified its generated email addresses, and they will now follow the format three-word-addresses@duck.com instead of the previous fixed-length format (e.g. vcb35uk3@duck.com).

fix(duckduckgo-email-protection): address parsing

---

documentation/OUTPUTMODES.md

Fixes a typo; we're probably referring to [ANSI colors](https://en.wikipedia.org/wiki/ANSI_escape_code#Colors).
–
–

Fix typo "ANSII"

---

commands/conversions/rich-text-clipboard-to-markdown.sh

Fix the error of executing rich-text-clipboard-to-markdown.sh according to [stackoverflow](https://stackoverflow.com/questions/2545289/getting-rtf-data-out-of-mac-os-x-pasteboard-clipboard).
```
0:23: execution error: Can’t make some data into the expected type. (-1700)
```

fix(rich-text-clipboard-to-markdown.sh): execution error

---

commands/apps/safari/safari-download-url.applescript

Script to download current url in safari. This is non-obvious.
NA
NA

download current safari url

---

commands/navigation/hide-application.applescript

This command hides the frontmost app.  This is useful if you want to remap the default Hide menu command keyboard shortcut: `command + h`.

Hide Application

---

commands/developer-utils/aws/amazon-s3-download.sh

This PR improves the `amazon-s3-download` script:
- if the URL like `s3://bucket/foo/bar/baz.json` points to a file `baz.json`, it will download the file as `Downloads/baz.json` instead of creating the full directory structure `Downloads/bucket/foo/bar/baz`
- if the URL like `s3://bucket/foo/bar` points to a folder `bar`, it will download the entire folder as `Downloads/bucket/foo/bar/*`
- if the URL like `s3://bucket` includes no key, it will download the entire bucket as `Downloads/bucket/*`
File download:
https://github.com/user-attachments/assets/f7c1e337-f621-4259-9202-d3f89a4db126
Folder download:
https://github.com/user-attachments/assets/c7b98e56-abbf-43ca-a823-52e4a3cbf21d
Bucket download:
https://github.com/user-attachments/assets/037e3d86-ae98-496a-a965-7de5339551ee

fix(amazon-s3-download): handle file, folder and bucket downloads

---

commands/system/otp.sh

This command copies One-Time Password for specified domain from Apple Password Manager.
Requires installation of [Apple Passwords CLI](https://github.com/bendews/apw) wrapper of Apple Passwords Manager.
It also requires `jq` that can be also installed from homebrew.

Add OPT command (One-Time Password) in system folder

---

commands/system/dismiss-notifications.applescript

This dismiss-notifications script stopped working for me on macOS Sequoia.
I've updated the script with the following code.

Update dismiss-notifications.applescript to work on Sequoia

---

commands/media/lowfi/lowfi.sh

Script command for start [lowfi](https://github.com/talwat/lowfi) command in a wezterm window, run the second time to bring the lowfi window to the front
Require
- [lowfi](https://github.com/talwat/lowfi)
- [WezTerm](https://wezfurlong.org/wezterm/index.html)

add lowfi command

---

commands/communication/emojis/random-emoji.sh

- Choice emoji randomly and copy to clipboard.
* [curl](https://curl.se/)
* [jq](https://jqlang.github.io/jq/)

Add Random Emoji command

---

commands/system/sleep-timer.applescript

Added a script command that puts Mac to sleep after X minutes. Replicates existing `Sleep` Raycast command but adds a timer.
No dependencies.

Added sleep timer script command

---

commands/communication/emojis/random-emoji.sh

Old version bash does not support `mapfile` command, so I've changed to use `read` .
- curl
- jq

Update random-emoji to support old bash

---

commands/system/dismiss-notifications.applescript

Handle groups of stacked notifications
The dismiss-notifications script could only handle a single, unstacked notification lingering on screen. This update adds support for clearing groups of stacked notifications.

feat: update dismiss notifications script

---

commands/system/toggle-natural-scrolling-macos15.applescript

The existing `toggle-natural-scrolling.applescript` fails on macOS 15.6.1+ with error:
```
The domain/default pair of (kCFPreferencesAnyApplication, com.apple.swipescrolldirection) does not exist
```
Added a new script `toggle-natural-scrolling-macos15.applescript` specifically for macOS 15+, while **preserving the original script** for backward compatibility.
- **Preserve existing functionality** for macOS 14 and earlier users
- **Clear version targeting** - users know which script to use  
- **Safe migration path** - no risk of breaking existing setups
- **Future-proof approach** - easier to maintain version-specific fixes
Through systematic debugging, we found that macOS 15.6.1+ changed the storage location:
**Old location (macOS ≤14):**
```bash
defaults -currentHost read …
```

Add natural scrolling toggle script for macOS 15.6.1+
