raycast/script-commands

system/toggle-dark-mode.applescript
Open Raycast and type "toggle system appearance".
The system will alternate between the light mode and the dark mode.
=> Add command to toggle dark mode

system/screensaver.sh
With the `Screen Saver` command, you will be able to start your current screen saver.
=> System: Add script for starting screen saver

.github/workflows/documentation.yml, Makefile, Tools/Toolkit/toolkit, toolkit
The main goal of this pull request is the creation of the Makefile to make it easier the process of building and generation of documents using [Raycast Toolkit](https://github.com/raycast/script-commands/tree/master/Tools/Toolkit). Also, I updated the workflow instructions on documentation.yml.
=> Update process of building and document generation

developer-utils/record-simulator.sh
Added links & a tiny description, also now the script asks the user for confirmation to run (I think the alert is needed because the script will save a file on the user's device)
=> Record simulator script improvements

conversions/hex-to-rgb.sh, conversions/hex-to-rgba.sh
See https://github.com/raycast/script-commands/pull/16#discussion_r516979718 and #24.
=> Address some feedback in merged PRs

README.md, Tools/Toolkit/Sources/ToolkitLibrary/Toolkit.swift, templates/script-command.template.sh, templates/script-command.template.swift
In this PR I've added:
- the new metatags in the template files
- templates folder into the blocked list
- update README adding new metatags
=> Metadata documentation

developer-utils/github-unread-notifications.sh
While output of total number of notifications is fine, we can do better: output total number per [notification reason](https://docs.github.com/en/free-pro-team@latest/rest/reference/activity#notification-reasons).
=> Add detailed output for GitHub Unread Notifications command

developer-utils/get-external-ip-v4.sh, developer-utils/get-external-ip-v6.sh, developer-utils/get-local-ip-v4.sh, developer-utils/get-local-ip-v6.sh
Because of the _Copy Output_ action (`CMD+.`) enhance the IP address commands to use `inline` mode.
=> Enhance IP address commands to use inline mode

communication/imessage-2fa.sh
Get most recent two-factor authentication code from iMessages.
=> Add Script Command: imessage-2fa

.github/pull_request_template.md
Simple template for new pull requests to make it easier to review.
—
Created via [Raycast](https://www.raycast.com?ref=signatureGithub)
=> Introduce template for PR

CONTRIBUTING.md
—
Created via [Raycast](https://www.raycast.com?ref=signatureGithub)
=> Introduce contribution guidelines

conversions/epoch-to-human-date.sh
Example: Convert 1605146036 to 2020-11-12 09:53:56
=> Add Script Commands: Convert epoch to human readable date

commands/developer-utils/google/google-lighthouse.sh, commands/developer-utils/google/google-psi-desktop.sh, commands/developer-utils/google/google-psi-mobile.sh
=> Remove local flags

CONTRIBUTING.md, README.md
An update to our guidelines for the use of login shells. I added the information to the contribution guidelines as well as added an hint to the README to make sure that new contributors now how to handle it.
Additionally I created #77 to keep track of our work on support for env variables.
—
Created via [Raycast](https://www.raycast.com?ref=signatureGithub)
=> Add guidelines for use of login shells

commands/communication/imessage-2fa.sh
Just an update in the metadata.
Nothing was changed.
Nothing was changed.
=> Update metadata for the imessage-2fa script command

commands/system/largest-cpu-process.sh, commands/system/largest-ram-process.sh
Please write a short summary for this change. If it's a new script command, explain what it does.
- `ps` command
- `awk` command
=> Add Script Commands: largest-cpu-process, largest-ram-process

.github/pull_request_template.md
Use comments in PR template to cleanup PR submissions and make faster for submitters.
=> Comment PR template instructions

commands/conversions/hex-to-rgb.sh, commands/conversions/hex-to-rgba.sh
Conversion wasn't working. Not sure what changed, but using a different approach that now works.
=> Shift to a different approach for HEX to decimal conversion

commands/developer-utils/add-ssh-keys.template.applescript
AppleScript to open a Terminal window and run commands to add multiple keys to the SSH agent.
=> Add Script Command Template: add-ssh-keys

commands/developer-utils/brew/brew-doctor.sh, commands/developer-utils/brew/brew-outdated.sh, commands/developer-utils/brew/brew-services-list.sh, commands/developer-utils/brew/brew-services-start.sh, commands/developer-utils/brew/brew-services-stop.sh, commands/developer-utils/brew/brew-upgrade.sh
A small list of script commands to help the use of Homebrew.
- [Homebrew](https://brew.sh)
=> Add Script Commands to support Homebrew

commands/dashboard/countdowns/countdown-to-christmas.sh, commands/dashboard/countdowns/countdown-to-date.template.sh, commands/dashboard/countdowns/create-countdown.template.sh
Here are 3 new scripts that allow you to create or display countdowns.
- **countdown-to-christmas:** Allows to see the number of days left until Christmas.
- **countdown-to-date:** A template that allows to see the number of days/hours left until a specific date.
- **create-countdown:** A template that allows countdown-to-date.sh files to be created automatically by entering a name and date.
- Event Name
- Event Date
- Coreutils
- Absolute path to the folder of the user Raycast script
=> Add Script Commands: countdown-to-christmas, countdown-to-date, create-countdown

.github/workflows/check-scripts-executable.yml, Tools/check-scripts-executable.sh
@unnamedd @thomaspaulmann 
GitHub Action to check and set permissions of all files (except documentation and images) in `commands` directory to be executable.
=> Auto check scripts and set executable

README.md
Direct the user to the templates directory for additional examples, specifically for "Passing Arguments" section of README.
=> Direct the user to the templates directory for additional examples

templates/script-command.template.applescript
Add script template for AppleScript
=> Add script template for AppleScript

commands/media/apple-tv/apple-tv-play-movie.applescript
=> Add Script Command: play-movie

templates/script-command.template.py, templates/script-command.template.rb
Add script templates for the ruby and python programming languages.
N/A
python3 and ruby installed
=> Add Python and Ruby templates

LICENSE
Signed-off-by: Matthew Gleich <email@mattglei.ch>
Simply change the license year
N/A
N/A
=> 📄 Update license year to 2020-2021

Tools/Toolkit/Tests/ToolkitLibraryTests/ToolkitLibraryTests.swift
Signed-off-by: Matthew Gleich <email@mattglei.ch>
Fix the basic unit tests for the Toolkit. Important for WIP documentation upgrades.
Look at those green checks!
N/A
=> ✅ Fix basic Unit Test for the ToolkitLibrary

commands/dashboard/world-time.sh
Show the time from elsewhere in the world. It's configurable by changing the time zones.
N/A
=> Add script command: Show the time from elsewhere in the world

commands/developer-utils/whois.sh
Just updating the `whois` script to use the macOS installed bin.
=> Update whois script

commands/developer-utils/dig.sh
This command perform a `dig` with the specified name and an optional second argument (usually the type).
This step depends solely on the _dig_ command, which comes with the standard developer tools. I think this dependency is expected and unavoidable.
=> feat: add dig command

commands/media/apple-music/apple-music-current-track.applescript
Add script command for current track in apple music.
=> Add script command for current track apple music

Tools/Toolkit/CONTRIBUTING.md, Tools/Toolkit/README.md
Vastly improved the toolkit docs by giving an explanation of what the toolkit does and detailed steps on how to contribute.
N/A
N/A
=> Improve Toolkit Documentation

commands/developer-utils/brew/brew-install.sh
A script that installs a brew package 
Brew has to be installed on the system.
=> Add a brew install script

commands/dashboard/world-time.sh
This way the preferred version of bash will be used. 
Probably would be good to change all of the scripts.
=> Prefer env bash over just bash

commands/system/toggle-mic.applescript
Toggles microphone on/off
No additional steps required. Just toggle and enjoy!
=> Add a script to toggle microphone on/off

commands/system/new-email.sh
Opens default email application, and creates a new email with the given inputs.
No dependencies.
=> Feature: Add new email

commands/dashboard/crypto-portfolio.py
This script command retrieves the latest prices for multiple cryptocurrencies from Binance and displays it inline.
None, except python3
=> Add script to fetch crypto prices from binance

commands/system/add-spacer-to-dock.sh
This is a simple utility script that adds an invisible icon to the Dock that acts as a spacer.
https://user-images.githubusercontent.com/32957606/110048788-5fc53400-7d05-11eb-92ac-8e0d071bb660.mov
=> New Script: add-spacer-to-dock.sh

commands/system/restart-dock.sh
This script restarts the Dock.  
There are no dependencies.
=> Simple script to restart the dock

commands/system/restart-dock.sh
I've aligned the output with the restart Dock script command.
=> silence output similar to PR for restart Finder

commands/system/restart-finder.sh
Simple script command to restart the Finder.
No dependencies
=> Simple script command to restart Finder

commands/developer-utils/tldr.sh
This script allows you to quickly get help on a shell command.
https://github.com/dbrgn/tealdeer
=> Add tldr integration

commands/developer-utils/brew/brew-list.sh, commands/developer-utils/brew/brew-update.sh
=> another brew commands

commands/web-searches/rust-crate.sh
Just fixed the URL in the description.
N/A
N/A
=> 💬 Fix rust crate URL in description

commands/system/open-folder.sh
Open a folder
Enter the full path of the folder
=> add script-command: open a folder

commands/system/open-folder.sh
I submitted issue (#331) and I fixed the script-command that I submitted. 
There is an extra space here.
=> fixed bug related to this issue (#331)

commands/system/quit-all-apps.swift
Optimization of the script for closing open applications. Better performance by making a single filter.
=> [REFACT] Optimization of the script for closing open applications

commands/web-searches/amazon.sh
Improve the existing “Search in Amazon” script amazon.sh by adding "percentEncoded": true.
=> Add "percentEncoded": true to Search in Amazon

commands/system/toggle-do-not-disturb.sh
Toggle system "Do not disturb", works for Big Sur
Brew package
[calm-notifications](https://github.com/vitorgalvao/tiny-scripts/blob/master/calm-notifications)
=> New Script: Toggle Do not disturb

commands/developer-utils/ignore-package-folders-time-machine.template.sh
Since the script requires changes to work, I think it makes more sense to be a template.
=> File is now a template and DEPTH a variable

commands/conversions/zalgo-text.swift
Converts text to z͚̳ͤ̓͐a̳̺ͥl̞̪͗͊g̀ͮ̇͌o͍ͧ t̜͕̱͐̑̏e̢͚̠̜ͩͯx̖ͦ͜͟͝ṱ̤̺ͩ͆̌
None
=> text → z͚̳ͤ̓͐a̳̺ͥl̞̪͗͊g̀ͮ̇͌o͍ͧ t̜͕̱͐̑̏e̢͚̠̜ͩͯx̖ͦ͜͟͝ṱ̤̺ͩ͆̌ command

commands/apps/dnd-me/start-dnd-me.sh, commands/apps/dnd-me/stop-dnd-me.sh
Two scripts to start and stop DND via [DND Me](https://runtimesharks.com/projects/dnd-me).
=> Scripts for DND Me

commands/system/toggle-natural-scrolling.applescript
Script Command to change natural trackpad/mouse scrolling setting.
The script reverts the setting value each time.
https://user-images.githubusercontent.com/1015148/116467698-5a3c2400-a846-11eb-96f7-d57f000c7c3f.mov
None.
=> Add "Toggle Natural Scrolling" command

commands/apps/espanso/espanso-create-expansion.sh
https://espanso.org is an open-source text expansion app. This script allows users to quickly add new text expansions to it from Raycast!
- Users have to have Espanso installed
=> Add "Create text expansion" script with Espanso

commands/system/modify-extension.sh
+ new script command:
+ commands/system/modify-extension.sh:
+ Batch modify the file in the current directory or the specified extension of the selected file
+ You must enter the search extension in 'Before' and the modified extension in 'After'
=> Batch modify file extension

commands/web-searches/search-coinmarketcap.sh
Created a simple script to search CoinMarketCap for cryptocurrencies. 
https://user-images.githubusercontent.com/49143413/116995719-01203480-ad0d-11eb-9b91-60c9a23ddbc1.mov
No dependencies
=> Create coinmarketcap search script

commands/navigation/open-terminal-from-finder.applescript
Improved the script to better detect what can be opened.
=> Fixed open finder in terminal script

commands/navigation/open-terminal-from-finder.applescript
Added Code to clear the terminal executed commands. In this case `cd {dir}` command
Before Code Optimization
After Code Optimization
=> Cleared Terminal executed command

commands/developer-utils/ignore-package-folders-time-machine.template.sh
I haven't found a way to totally automate this, but this is _really_ close to a seamless process. Once in a while just check of the Smart Folder has items in it and if yes, go to Spotlight -> Privacy and drag all the results in.
=> Added Spotlight tagging to excluded folders

commands/web-searches/check-weather.sh
Add weather checker using https://wttr.in
=> Add weather checker

commands/apps/ferdi/ferdi-open-service-by-index.applescript, commands/apps/ferdi/ferdi-open-service-by-name.applescript
Add Ferdi Service Opener by Name & Update Ferdi Service Opener by Index
Ferdi installed
=> Add Ferdi Service Opener by Name

commands/home/philips-hue/hue-bulb.template.mjs, commands/home/philips-hue/hue-room.template.mjs
Sorry for the quick change after submitting this earlier - just noticed that I could make the scripts a bit clearer by using JSON.stringify() instead of doing it explicitly myself with template literals.
=> Minor Philips Hue script improvements

commands/communication/slack/slack-open-workspace-by-index.applescript, commands/communication/slack/slack-open-workspace-by-name.applescript
Add Slack Workspace Opener by Index & Name
Slack installed
=> Add Slack Workspace Opener by Index & Name

commands/apps/ferdi/ferdi-open-service-by-name.applescript
Minor changes to Ferdi Service Opener (whitespaces, improved condition)
=> Minor changes to Ferdi Service Opener

commands/developer-utils/gitlab/gitlab-issues.template.py, commands/developer-utils/gitlab/gitlab-mergerequests.template.py, commands/developer-utils/gitlab/gitlab-todos.template.py
Update on the Gitlab Script Commands for MR, Issues, Todos, adds url to all, and description and author to MR.
Not adding screenshots since it's not a new script.
No new deps
=> Improve Gitlab script commands adding links, description, etc

commands/apps/todoist/create-task.template.sh
Added the ability to change due date to a todoist-formatted thing.  Defaults to "Tomorrow" as before
n/a
=> added ability to change due date

commands/web-searches/im-feeling-ducky.sh
Add an "I'm feeling lucky feature to raycast using DDG search engine
https://user-images.githubusercontent.com/17577332/119268716-82743400-bbf4-11eb-83d5-06494826c5b3.mp4
=> Add I'm feeling lucky cmd using ddgr

commands/README.md, commands/system/kill-process.sh
New script command that accepts one argument (process name) and force kills a running process with that name
No dependencies.
=> Added a command to force kill a process

commands/apps/fantastical/create-todo-in-fantastical.applescript
Simply allows you to create a todo/task for the same day in Fantastical. 
https://user-images.githubusercontent.com/46573539/120586394-76ad1c80-c401-11eb-8fe7-28fd7c379d42.mov
N/A
=> Added Task/ToDo Creation script for Fantastical

commands/system/wallpaper-refresh.applescript
=> Improve wallpaper-refresh script description

commands/developer-utils/docker/clean-docker.sh
Basic shell script that clean everything related to docker (images, containers, volumes).
=> Added script that cleans docker data

commands/developer-utils/clear_xcode.sh
=> feat: clear xcode related junk script

commands/apps/pulse-secure/pulse-secure-connect.applescript
=> [Pulse Secure] Make password argument secure

commands/password-managers/bitwarden/create-text-send.sh, commands/password-managers/bitwarden/log-in.template.sh, commands/password-managers/bitwarden/receive-text-send.sh, commands/password-managers/bitwarden/unlock.sh
=> [Bitwarden] Make password arguments secure

commands/password-managers/bitwarden/log-in.template.sh
=> [Bitwarden] Make MFA code g̶r̶e̶... plain text again

commands/conversions/create-gif-from-video.py
Converts a video file to a gif file using [gifski](https://github.com/ImageOptim/gifski), arguments are all optionals, first one is source file path, second on is destination file path, and last one is resulting gif fps number.
By default, it takes the last video file on Desktop. I've done that to easily convert screen videos.
Needs [gifski](https://github.com/ImageOptim/gifski) to work.
=> Added create gif from video script

commands/developer-utils/ip/get-external-ip-v4.sh, commands/developer-utils/ip/get-external-ip-v6.sh, commands/developer-utils/ip/get-local-ip-v4.sh, commands/developer-utils/ip/get-local-ip-v6.sh
removes the `refreshTime` parameter, causing the command to update your clipboard once an hour.
=> fix ip scripts 

README.md, commands/README.md, commands/apps/ferdi/ferdi-open-service-by-index.applescript, commands/apps/ferdi/ferdi-open-service-by-name.applescript, commands/apps/wikipedia/wikipedia-search.py, commands/communication/messenger/messenger-open-conversation.applescript, commands/communication/slack/slack-jump-to.applescript, commands/communication/slack/slack-open-workspace-by-index.applescript, commands/communication/slack/slack-open-workspace-by-name.applescript, commands/conversions/rich-text-clipboard-to-markdown.sh, commands/dashboard/twitter-statistics.template.rb, commands/home/philips-hue/hue-bulb.template.mjs, commands/home/philips-hue/hue-lights-inline.template.mjs, commands/home/philips-hue/hue-room.template.mjs, commands/home/philips-hue/hue-rooms-inline.template.mjs, commands/navigation/open-finder-from-terminal.applescript, commands/system/open-selection-with.applescript, commands/system/sidecar-toggle.template.applescript, commands/system/update-scripts-command.template.py, documentation/OUTPUTMODES.md
Changing British English into American English.
=> American English

commands/developer-utils/unix-timestamp.sh
Copy current epoch Unix timestamp.
None
=> Add script command: unix-timestamp.sh

commands/developer-utils/git/git-standup.sh, commands/system/default-browser-front-most-app.applescript
=> Improve default browser front most app

commands/developer-utils/git/git-standup.sh
=> Improve git-standup sh

commands/apps/phpstorm/.gitignore, commands/apps/phpstorm/recent-projects.sh
Script to get latest 20 PhpStorm projects into Raycast using Raygen
Raygen (https://github.com/pomdtr/raygen) and PhpStorm installed via JetBrains Toolbox
=> Latest 20 PhpStorm projects

commands/apps/things/things-create-todo.sh
Allows you to add notes to your Things task. 
closes #540 
https://user-images.githubusercontent.com/8660142/128770462-d6e68fdb-6b4e-4e43-b725-03e5c082e22e.mov
N/A
=> Support adding notes to a Things task

README.md
This PR fixes a teeny tiny typo
=> fix: a tiny typo

commands/apps/notes/create-note-from-clipboard.applescript
This script allows creating a new note from the clipboard
https://user-images.githubusercontent.com/841163/129803890-474ad540-db54-4e2e-b731-7e42f4c8d792.mov
=> add script to create note from clipboard

commands/developer-utils/github/github-unread-notifications.template.sh
=> Shorten review_requested reason for GitHub Unread Notifications script

commands/conversions/trim-newlines-tabs.sh
Remove newlines and tabs from clipboard content.
=> Add Script Command: trim-newlines-tabs.sh

commands/apps/meetingbar/meetingbar-create-meeting.applescript, commands/apps/meetingbar/meetingbar-join-meeting.applescript
=> [MeetingBar] Update installation instructions

commands/apps/notes/append-note-from-clipboard.applescript
This script appends clipboard content to an existing note.
https://user-images.githubusercontent.com/841163/130296709-e0fd8a02-4910-413c-87a1-38a549247cb6.mov
=> add script append-note-from-clipboard

commands/developer-utils/time-between-dates.js, commands/developer-utils/time-calculator.js
Given two dates (the first is optional, the default value is today) the script returns the time between them in different unit of measure.
The result will be in milliseconds, hours, days and years.
Given a date (optional, the default value is today) the script allows you to add or subtract an amount of time specifying the unit of measure choosing from Seconds, Minutes, Hours, Days, Weeks, Years.
The result will be the resulting date and time as well as the unix time.
Install Nodejs
=> Add Scripts for time calculation

commands/communication/zoom/mute-mic.applescript, commands/communication/zoom/toggle-mic.applescript, commands/communication/zoom/toggle-video.applescript
Two new scripts to toggle video and microphone in the current Zoom meeting
=> Add toggle video and toggle audio Zoom commands

templates/script-command.template.rb
Add example to ruby template of how to accept a script argument
=> Add example of how to accept an argument to script

commands/system/disk-free.sh
Adapted Disk Free Alfred workflow to work in raycast.
I´ve added console colors for a better experience.
No dependencies needed.
=> add disk-free system script

commands/productivity/tesseract/tesseract-ocr.sh
Added a script that extract text from screenshot to clipboard using [Tesseract OCR](https://github.com/tesseract-ocr/tesseract)
Requires installation of [Tesseract OCR](https://github.com/tesseract-ocr/tesseract)
can be done by [brew install tesseract](https://formulae.brew.sh/formula/tesseract)
=> add tesseract ocr script command

commands/system/nightshift.sh
This script allow you to on/off (toggle) the night light setting for you display.
This script requires `nightlight` to be installed: https://github.com/smudge/nightlight
Install via homebrew: `brew install smudge/smudge/nightlight`
=> Add Night Light toggle command

commands/README.md, commands/system/wifi-password.sh
A very simple script to copy the WIFI Password from your current session. 
Inspired by @rauchg
=> Add WIFI Password script command

commands/apps/deepl/deepl-app-translate.applescript
Update the script's UI element targets to fix breaking changes made in a recent DeepL app update.
=> Update DeepL app script for DeepL 2.7.95892

commands/system/toggle-ds-store.applescript
A script command to enable and disable .DS_Store
=> Add Toggle .DS_Store script command

commands/productivity/macocr/macocr-run-ocr.sh
Add OCR with `macOCR`
[macOCR](https://github.com/schappim/macOCR)
=> Add macOCR

commands/system/do-not-disturb.sh
Set default command to "toggle".
=> Update Do Not Disturb command

commands/developer-utils/generate-ulid.sh
Add script to generate a `Universally Unique Lexicographically Sortable Identifier` using [ulid](https://github.com/ulid/javascript)
It requires to have [ulid](https://github.com/ulid/javascript) installed
=> Add script to generate a ULID

commands/apps/iconsur/iconsur.sh
Support for Applications under User/Applications folder. Updated error message.
=> Update script iconsur

commands/media/apple-music/apple-music-volume-down.applescript, commands/media/apple-music/apple-music-volume-up.applescript
Two new script commands to change the volume of Apple Music
- New script command
No screenshot, is a silent command.
No dependencies or requirements.
=> Script commands to change the volume of Apple Music

commands/developer-utils/run-command-in-finder.sh
=> fix: set default location to desktop when no window

commands/writing/word-count.sh
Adds a simple word count command for text in the clipboard.
None
=> Add a word count script

commands/apps/deepl/deepl-app-translate.applescript
Updates the script's GUI targets to reflect changes made in a recent DeepL app update. 
Fixes #673
=> Fixes for DeepL 3.1.133440

commands/browsing/shlink-create-short-url.template.sh
Adds a description for shlink-create-short-url.template.sh, so it can be found easier on websites like [scriptcommands.com](https://scriptcommands.com)
=> [Shlink] Improve documentation for shlink-create-short-url.template.sh

commands/dashboard/fear-index.sh
This script will show the latest data from CNN Fear & Greed Index 
No Dependencies or Requirements
=> Add Fear & Greed Index Script

commands/apps/terminal-translate/translate.sh
Require install terminal-translate by `npm install terminal-translate -g`
=> feat(command): add tl 

README.md
Quick grammar tweak to make things more readable
=> Clarify wording on README extensions highlight

commands/system/save-image-from-clipboard.py
Save Image from Clipboard to your local Downloads folder.
This command requires the installation of `Pillow` Python module: 
```bash
python3 -m pip install Pillow
```
=> Add Save Image from Clipboard

commands/apps/raycast/celebrate.sh
Set Confetti run times and intervals
Raycast >= 1.35.0
=> add Celebrate script

commands/dashboard/current-weather.sh
As discussed on #739 this updates the geo location for the current weather script
=> Updated current-weather to use better geo location

commands/developer-utils/get-ttfb.sh
This command will execute a lookup at a given domain and return details about connection time, ssl handsake time and time to first byte.
None (Uses system provided curl)
=> Add get-ttfb command

commands/apps/mullvad/connect.sh, commands/apps/mullvad/location.sh, commands/apps/mullvad/reconnect.sh, commands/apps/mullvad/status.sh
The existing mullvad script did not correctly display the status when connected to the VPN.
=> Fix ‘mullvad status’ issues

commands/media/tidal/tidal.applescript
I needed a script for Tidal but didn't like the idea of having two scripts for a simple task.  
Having tried other scripts, I liked the little emoji that popped with the silent compact modal.  
Basically :   
- Merged both existing scripts, made by Charles Harries  
- Simplified the code  
- Added two emoji logs  
- [√] New script command  
- [√] Improvement of an existing script  
- [√] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)
=> Added simplified Tidal script

commands/browsing/new-browser-window.sh
This script opens a new window into your default browser
plutil, grep, awk, open
=> ✨Added a way to open browser window

commands/browsing/open-in-guest-profile.sh
Open the current website in guest profile/mode
https://user-images.githubusercontent.com/47495003/198998301-1f89b59d-630b-4bae-9e93-47fb54c6a5e6.mov
N/A
=> feat(browsing): Open in guest profile

commands/culture/prayer-times-diyanet.sh, commands/productivity/prayer-times-diyanet.sh
This command grabs prayer times from the Diyanet's Official Website for people located in Türkiye.
> You may need to install coreutils via homebrew to make this script work (gdate function).
* Homebrew: https://brew.sh/
* Coreutils: https://formulae.brew.sh/formula/coreutils
=> Prayer times diyanet command

commands/system/network-quality.sh
=> Fix network-quality script

commands/developer-utils/get-ttfb.sh
Use https scheme while checking for TTFB if no schema is given.
=> update get-ttfb command

README.md
Fix typo "troubleshouting" => "troubleshooting" :)
=> Fix typo in "troubleshooting"

commands/communication/mail/open-most-recent-email.applescript
Open the last received email in Mail.app. Trigger a check for new email if there are no messages.
=> Add open-most-recent-email script command

commands/apps/one-thing/one-thing-clear-text.sh
Added another command for my One Thing app.
=> Add `Clear Text` command for One Thing app

commands/dashboard/tesla.template.sh
A new script command, which provides the status of your Tesla vehicle
For the script to work, you need to get the a refresh token. Process of how to do so, is described in the script file.
=> Added a new script for getting the status of a Tesla Vehicle

commands/apps/safari/safari-bing-edge-user-agent.applescript
Open Bing in Safari with Edge User-Agent, check Safari - Advanced - Develop first. This script works on the English Safari menu.
=> Open Bing in Safari with Edge User-Agent

commands/developer-utils/is-it-up.sh
Add the option for users to be notified of the status through system notification and changed wording of messaging for clarity.
Improvement of script to add functionality
Improvement of an existing script
- [ x ] I have read [Contribution Guidelines](https://github.com/raycast/script-commands/blob/master/CONTRIBUTING.md)
=> Enhanced clarity on is-it-up.sh

commands/apps/todoist/create-task.template.sh
fix todoist/create-task.template.sh script:
add new task api call: https://developer.todoist.com/rest/v2#adding-a-new-task
=> upd create-task.template.sh

commands/dashboard/open-ai-usage.sh
check your total usage of OpenAI API
This script requires `jq` cli installed: https://stedolan.github.io/jq/
Install via homebrew: `brew install jq`
This script requires `Open API Key` and `ORGANIZATION`
plsease fillout above in the script before you start to use this script.
=> add check open api usage

commands/system/Low Power Mode.sh
This is a script that toggles Low Power Mode on and off.
It also changes the brightness back to 100% after turning off Low Power Mode.
https://github.com/raycast/script-commands/assets/68571978/93253bee-5757-48ae-aef6-376b398335ae
None
=> Low Power Mode script

commands/conversions/raw-html-to-rich-text-clipboard.sh
- feat: convert raw html on clipboard to rich text
- fix: adding dependency notice
This script will convert raw HTML on your clipboard to rich text.
Follow-up from: https://github.com/raycast/script-commands/pull/841
NA
Requires pandoc
=> feat: html to rich text on clipboard

commands/system/Network Info.sh
This script get details about the current network(IP address, ISP, city, region, country, postal code)
I haven't yet found a way to get the name of the current wifi network programmatically. If anyone finds a way, please leave a comment.
None
=> Network Info.sh

commands/developer-utils/github/github-repository-stars_all_repos_template.rb
Get all stars, forks, subscribers for all repos by owner repository## Type of change
Access token
Owner Repository name
=> All repos stars

commands/conversions/google-docs-to-markdown.sh
Script to convert google docs html to markdown
NA
Indicated in the script: https://github.com/Mr0grog/google-docs-to-markdown
=> feat: adding google docs to markdown

commands/math/calculate-combinations.js
A script command that calculates nCr for the given arguments.
Needs Nodejs to be installed as it is a js script.
=> ✨ new command: combinations calculator

commands/system/default-browser-firefox.applescript
default browser firefox is Incorrect, set firefox
=> fix : default browser firefox is Incorrect

commands/conversions/inputs-to-markdown-link.sh
This change introduces updates to the script command. Firstly, a description has been added for its purpose and functionality. Additionally, a default title has been set, and the title argument has now been made optional, enhancing user flexibility when utilizing the script.
=> Improvement: Add Description and Set Default Title with Optional Argument

commands/system/audio/toggle-mute-notification-sounds.applescript
This script toggles muting notification sounds (Slack messages, iMessage texts, etc.).
Notification on muting sound:
=> Toggle mute notification sounds

commands/web-searches/search-script-command-marketplace.sh
=> Fix `search-script-command-marketplace` domain

commands/media/apple-music/apple-music-love-current-track.applescript
Apple Music has seemingly changed their properities data since the time of writing this script. Found this useful util here to gather all the available information that could be modified
```
tell application "Music" to get properties of current track
```
=> update the script API for apple music love song action to match current properities

commands/system/inline-cpu-usage-percent.sh
=> feat: add inline-cpu-usage-percent script

commands/culture/prayer-times.sh
Replace source of the API with more stable and comprehensive one.
=> Update and rename prayer-times-diyanet.sh to prayer-times.sh

commands/system/copy-selection-to-clipboard.applescript
Copy contents of selected file to clipboard.
N/A
Pure applescript.
=> system: copy selected finder file(s) to clipboard

commands/math/calculate-CAGR.sh
This is a simple script command that calculates the compound annual growth rate (CAGR) based on three values entered by the user: starting value, ending value, and years. This is a calculation I find myself using often, so I made myself a Raycast script command for it. It might be broadly applicable and useful for others, so I want to contribute it. 
N/A
=> Add CAGR calculation script within math folder

commands/system/rename-vedios-pictures.py, commands/system/rename-videos-pictures.py
A recursive file renaming script that helps batch rename video and image files with a consistent date-based pattern. The script renames files to `foldername-MMDD-NN` format (e.g., `videos-1216-01.mp4`), where:
- `foldername`: name of the containing folder
- `MMDD`: current date in month-day format
- `NN`: sequential number starting from 01
Features:
- Recursively processes all subdirectories
- Supports common video and image formats
- Maintains existing renamed files
- Provides dry-run mode for preview
- Allows filtering by file type (video/image)
No additional dependencies required. The script uses only Python standard library.
=> Add a new script of rename-videos-pictures.py
